### PR TITLE
The complete Space Travelers'  Hub

### PR DESCRIPTION
**Pull request by Mofuhidy**
# What we did in this PR Me @Mofuhidy  and @tjay1760 :

- Fetches data from the SpaceX API and stores it in Redux
- Render lists of rockets, and missions.
- Allows users to reserve rockets and join missions
- Shows a "Reserved" badge and "Cancel reservation" button for reserved rockets
- Shows an "Active Member" badge and a "Leave mission" button for missions that the user has joined
- Lists all reserved rockets, and missions in the My Profile section

**Testing:**
- Covered key components and functionalities with unit tests using React Testing Library and Jest.
- Ensured all tests passed successfully.

**Thank you for your review!**

### CODE REVIEW

**Review by muneebulrehman — APPROVED** [review]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Descriptive PR
- Great job styling the project
- Great job memoizing the active missions.
- Clean code.
- All tests passing
- All technical requirements met for this project.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Mofuhidy** [comment]
Thank you very much for your review @muneebulrehman 😸

**Comment by Mofuhidy** [comment]
You Approved our project but in the dashboard, it does not change the button to submit @muneebulrehman ?

**Comment by muneebulrehman** [comment]
> You Approved our project but in the dashboard, it does not change the button to submit @muneebulrehman ?

@Mofuhidy, It should be approved by now. My internet went down the moment I was marking it as approved in the dashboard. Sorry for any inconvenience caused.

**Comment by Mofuhidy** [comment]
@muneebulrehman  Yeah now it's approved Thank you very much 😄🌹

**Pull request merged**
